name: Docker Image CI

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/sliit-kubernets-test:${{ github.sha }}
    - uses: actions-hub/kubectl@master
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context octobay-api
    - name: Deploy to K8s
      run: kubectl apply -f k8s/
      # env:
      #   KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      # with:
      #   args: get namespaces
   